"""更改 is_active 欄位(預設 False)

Revision ID: 29e2ee940577
Revises: 88e6fd3346c8
Create Date: 2026-01-30 22:51:27.654138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e2ee940577'
down_revision: Union[str, Sequence[str], None] = '88e6fd3346c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
