import jwt
from datetime import datetime, timedelta, timezone
from passlib.context import CryptContext
from app.core.config import settings
from app.core.metrics import CRYPTO_OP_DURATION

# Initialize Argon2 password hashing context
pwd_context = CryptContext(schemes=["argon2"], deprecated="auto")

SCOPE_USER = "user"
SCOPE_ADMIN = "admin"

@CRYPTO_OP_DURATION.time()
def verify_password(plain_password: str, hashed_password: str) -> bool:
    """
    Verify if a plain text password matches the stored hash.
    """
    return pwd_context.verify(plain_password, hashed_password)

@CRYPTO_OP_DURATION.time()
def get_password_hash(password: str) -> str:
    """
    Generate an Argon2 hash from a plain text password.
    """
    return pwd_context.hash(password)

def get_user_scope_string(is_superuser: bool) -> str:
    """
    Converts user privileges into an OAuth2 compatible scope string.
    Example: 
      - Normal user -> "user"
      - Admin -> "user admin"
    """
    scopes = [SCOPE_USER]
    if is_superuser:
        scopes.append(SCOPE_ADMIN)
    return " ".join(scopes)

def create_access_token(data: dict, expires_delta: timedelta | None = None) -> str:
    """
    Create a short-lived Access Token for API authentication.
    Signed with RSA Private Key (RS256).

    NOTE: The 'data' dict should normally contain:
          - sub: user_id or email
          - scopes: space-separated permissions (generated by get_user_scope_string)
    """
    to_encode = data.copy()
    
    if expires_delta:
        expire = datetime.now(timezone.utc) + expires_delta
    else:
        expire = datetime.now(timezone.utc) + timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)
    
    # Adding 'type' claim to distinguish between token categories
    to_encode.update({"exp": expire, "type": "access"})
    
    # IMPORTANT: Sign using PRIVATE KEY
    # We add the 'kid' to the header so the verifier knows which public key to use
    encoded_jwt = jwt.encode(
        to_encode, 
        settings.PRIVATE_KEY, 
        algorithm=settings.ALGORITHM,
        headers={"kid": settings.SIG_KEY_ID}
    )
    return encoded_jwt

def create_refresh_token(data: dict) -> str:
    """
    Create a long-lived Refresh Token (7 days).
    Signed with RSA Private Key (RS256).
    """
    to_encode = data.copy()
    expire = datetime.now(timezone.utc) + timedelta(days=7)
    to_encode.update({"exp": expire, "type": "refresh"})
    
    encoded_jwt = jwt.encode(
        to_encode, 
        settings.PRIVATE_KEY, 
        algorithm=settings.ALGORITHM,
        headers={"kid": settings.SIG_KEY_ID}
    )
    return encoded_jwt

def create_verification_token(email: str, purpose: str = "email_verification") -> str:
    """
    Create a token for specific purposes (email_verification, password_reset).
    Signed with RSA Private Key (RS256).
    
    Uses 'type' claim to distinguish purpose, keeping 'scope' free for permissions.
    """
    expire = datetime.now(timezone.utc) + timedelta(hours=24)
    
    to_encode = {"exp": expire, "sub": email, "type": purpose}
    
    encoded_jwt = jwt.encode(
        to_encode, 
        settings.PRIVATE_KEY, 
        algorithm=settings.ALGORITHM,
        headers={"kid": settings.SIG_KEY_ID}
    )
    return encoded_jwt

def verify_token_purpose(token: str, expected_purpose: str) -> str | None:
    """
    Generic function to verify a token's PURPOSE (type) and return the subject (email).
    Uses PUBLIC KEY for verification.
    """
    try:
        payload = jwt.decode(
            token, 
            settings.PUBLIC_KEY, 
            algorithms=[settings.ALGORITHM]
        )
        
        if payload.get("type") != expected_purpose:
            return None
            
        return payload.get("sub")
    except jwt.PyJWTError:
        return None

def verify_email_token(token: str) -> str | None:
    """
    Decode and verify the email verification token.
    Ensures the type is strictly 'email_verification'.
    """
    return verify_token_purpose(token, "email_verification")

def decode_token(token: str) -> dict | None:
    """
    Generic decode function to verify any JWT token generated by the system.
    Returns the payload if valid, otherwise returns None.
    Uses PUBLIC KEY for verification.
    """
    try:
        # Verify using PUBLIC KEY
        return jwt.decode(
            token, 
            settings.PUBLIC_KEY, 
            algorithms=[settings.ALGORITHM]
        )
    except jwt.PyJWTError:
        return None